### ISSUE TITLE
Quickstart guides (clickhouse, mysql) assume that the user already has a DB set up.

### ISSUE THREAD

**Issue by digadeesh** [spiceai/quickstarts#101]
It would be nice to have some easy set up (using docker for instance to pull mysql and clickhouse containers) so the user can very easily start with spice and whatever connector needed.  Found in Mysql,PostgreSQL, and clickhouse.

**Comment by Jeadie** [comment]
Fixed for Postgres.

**Comment by digadeesh** [comment]
Closing in favor of creating docs in Samples since it would be synthetic data.
