### ISSUE TITLE
Improvement: unity catalog quickstarts can based on local setup of unity

### ISSUE THREAD

**Issue by y-f-u** [spiceai/quickstarts#145]
[[unitycatalog/unitycatalog: Open, Multi-modal Catalog for Data & AI](https://github.com/unitycatalog/unitycatalog)](https://github.com/unitycatalog/unitycatalog) has a quickstart section, it might be better to align with it and start a local unity server to quickstart spice unity functions.

**Comment by phillipleblanc** [comment]
Quickstarts are designed to be quickly used with an existing service, samples are where more tutorial style setups go
