### ISSUE TITLE
Serverops quickstart e2e test is flaky

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/quickstarts#55]
The serverops quickstart e2e test is flaky.

In this run, attempt #2 was successful and attempt #1 failed - despite no differences between them:

Attempt 2 (succeeded): https://github.com/spiceai/quickstarts/actions/runs/1625609207
Attempt 1 (failed): https://github.com/spiceai/quickstarts/actions/runs/1625609207/attempts/1

On cursory investigation, it looks like the training doesn't complete in time before the test gets the recommendation, so the recommendation has a confidence of 0. Re-running the test can allow the training to finish in time and make it pass.

**Comment by lukekim** [comment]
Resolved. Tests have been stable for months now.
